In [16]:
import pandas as pd
import numpy as np

NUM_PROBLEMS = 5
NUM_ASSIGNMENTS = 2

In [17]:
cols = ['idiom_0',
       'instance_0', 'label_0', 'meaning_0', 'idiom_1', 'instance_1',
       'label_1', 'meaning_1', 'idiom_2', 'instance_2', 'label_2', 'meaning_2',
       'idiom_3', 'instance_3', 'label_3', 'meaning_3', 'idiom_4',
       'instance_4', 'label_4', 'meaning_4', '0_gold', '1_gold',
        '2_gold', '3_gold', '4_gold',
       'TimeMe', 'AssignmentId', 'WorkerId']

column_groups = [
        ['idiom_0', 'instance_0', 'label_0', 'meaning_0', '0_gold'],
        ['idiom_1', 'instance_1', 'label_1', 'meaning_1', '1_gold'],
        ['idiom_2', 'instance_2', 'label_2', 'meaning_2', '2_gold'],
        ['idiom_3', 'instance_3', 'label_3', 'meaning_3', '3_gold'],
        ['idiom_4', 'instance_4', 'label_4', 'meaning_4', '4_gold'],
    ]

# common columns for all rows
common_cols = ['TimeMe', 'AssignmentId', 'WorkerId']

In [18]:
def str_replace(df):
    df.columns = df.columns.str.replace('Input.', '') 
    df.columns = df.columns.str.replace('Answer.', '')
    return df

df = pd.read_csv("batch3_result.csv")
df = str_replace(df)
df = df[cols]
df = df.fillna('{}')
df.head()

/var/folders/92/6j34w0196yq0cnnrfrw0s68w0000gn/T/ipykernel_24660/4228242580.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df.columns = df.columns.str.replace('Input.', '')
/var/folders/92/6j34w0196yq0cnnrfrw0s68w0000gn/T/ipykernel_24660/4228242580.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df.columns = df.columns.str.replace('Answer.', '')

,idiom_0,instance_0,label_0,meaning_0,idiom_1,instance_1,label_1,meaning_1,idiom_2,instance_2,...,label_4,meaning_4,0_gold,1_gold,2_gold,3_gold,4_gold,TimeMe,AssignmentId,WorkerId
0,be on a collision course,their opposing political views put them on a c...,0,doing or saying things which are certain to ca...,feather one's (own) nest,she was accused of feathering her own nest by ...,0,If you say that you are feathering your own ne...,Dutch uncle,he dressed up like a Dutch uncle for the histo...,...,1,to understand that something is not completely...,0,0,1,0,1,115.322,3JBT3HLQFOIGF8N0VU0U6X7WMW7PZS,A1HKYY6XI2OHO1
1,be on a collision course,their opposing political views put them on a c...,0,doing or saying things which are certain to ca...,feather one's (own) nest,she was accused of feathering her own nest by ...,0,If you say that you are feathering your own ne...,Dutch uncle,he dressed up like a Dutch uncle for the histo...,...,1,to understand that something is not completely...,0,0,1,0,1,54.151,3X3OR7WPZFGB4R7FUC7ACW18IDZL8L,A290OV59Q76QC8
2,kick the bucket,"while cleaning the barn, they accidentally kic...",1,to die,axe to grind,the lumberjack had an axe to grind before chop...,1,have a private or selfish reason for doing som...,the sun rises and sets on them,"living on a remote island, the sun rises and s...",...,1,to do what someone else forces you to do,1,1,1,0,1,110.352,37Z929RLGPOH6OUTHJF6FEBQOKSSTV,A1HKYY6XI2OHO1
3,kick the bucket,"while cleaning the barn, they accidentally kic...",1,to die,axe to grind,the lumberjack had an axe to grind before chop...,1,have a private or selfish reason for doing som...,the sun rises and sets on them,"living on a remote island, the sun rises and s...",...,1,to do what someone else forces you to do,1,1,1,0,1,45.737,3SB5N7Y3OJKD0AOBOHXF6PQI3Y1G0N,A290OV59Q76QC8
4,over the moon,she was over the moon about the news of her pr...,0,extremely pleased or happy,big brother,"as the younger sibling, she was always watched...",1,A large organization or government agency that...,pull the plug,"due to budget constraints, the management deci...",...,1,when something is in danger and its enemies ar...,0,1,0,1,1,148.821,33UKMF931P0ILO786JKWPJ7CQ36TTL,A2LMQ4497NMK3S

In [19]:
def melt(df):
    # list of column sets

    # melt the dataframe
    dfs = []
    for i, column_group in enumerate(column_groups):
        melted = df[column_group + common_cols].copy()  # select the columns
        melted.columns = ['idiom', 'instance', 'label', 'meaning', 'gold',]+ common_cols  # rename the columns
        melted['group'] = i  # add a column to indicate the original group
        dfs.append(melted)

    # concatenate the melted dataframes
    df_melted = pd.concat(dfs, ignore_index=True)
    return df_melted.drop('group', axis=1)

df = melt(df)
df.head()

,idiom,instance,label,meaning,gold,TimeMe,AssignmentId,WorkerId
0,be on a collision course,their opposing political views put them on a c...,0,doing or saying things which are certain to ca...,0,115.322,3JBT3HLQFOIGF8N0VU0U6X7WMW7PZS,A1HKYY6XI2OHO1
1,be on a collision course,their opposing political views put them on a c...,0,doing or saying things which are certain to ca...,0,54.151,3X3OR7WPZFGB4R7FUC7ACW18IDZL8L,A290OV59Q76QC8
2,kick the bucket,"while cleaning the barn, they accidentally kic...",1,to die,1,110.352,37Z929RLGPOH6OUTHJF6FEBQOKSSTV,A1HKYY6XI2OHO1
3,kick the bucket,"while cleaning the barn, they accidentally kic...",1,to die,1,45.737,3SB5N7Y3OJKD0AOBOHXF6PQI3Y1G0N,A290OV59Q76QC8
4,over the moon,she was over the moon about the news of her pr...,0,extremely pleased or happy,0,148.821,33UKMF931P0ILO786JKWPJ7CQ36TTL,A2LMQ4497NMK3S

In [20]:
df = df.groupby(['idiom', 'instance', 'label', 'meaning']).agg(list).reset_index()
df['len'] = df['gold'].apply(len)
df['len'].value_counts()

2    500
Name: len, dtype: int64

In [21]:
from collections import Counter

def most_frequent(array):
    count = Counter(array)
    max_count = max(count.values())
    max_elements = [k for k, v in count.items() if v == max_count]

    if len(max_elements) > 1:
        return 'tie'  # return -1 in case of a tie

    return max_elements[0]  # return the most frequent element

In [22]:
labels = ['figurative', 'literal', 'ambiguous', 'discard', 'tie']
def f(row):
    for i in range(NUM_ASSIGNMENTS):
        row[f'gold_{i}'] = labels[row['gold'][i]]
    row['label'] = labels[row['label']]
    row['maxVote'] = most_frequent([
        row[f'gold_{i}'] for i in range(NUM_ASSIGNMENTS)])
    return row
df = df.apply(f, axis=1).drop('len', axis=1)
df.head()

,idiom,instance,label,meaning,gold,TimeMe,AssignmentId,WorkerId,gold_0,gold_1,maxVote
0,Dutch uncle,he dressed up like a Dutch uncle for the histo...,literal,"criticize, scold or lecture someone","[1, 1]","[115.322, 54.151]","[3JBT3HLQFOIGF8N0VU0U6X7WMW7PZS, 3X3OR7WPZFGB4...","[A1HKYY6XI2OHO1, A290OV59Q76QC8]",literal,literal,literal
1,Easter egg,"during the egg hunt, the child found an Easter...",literal,a decorated or dyed egg usually given to child...,"[0, 0]","[171.447, 112.306]","[3JCG6DTRVJ6S1SNO8BW6F9L2MP8QQQ, 3ERMJ6L4DE8RA...","[A2LMQ4497NMK3S, APRZ7BR8C0ZMQ]",figurative,figurative,figurative
2,"Mr Right, Ms Right","after years of searching, they finally found t...",figurative,the best future life partner for someone,"[0, 0]","[148.92, 38.074]","[3DY4FPOOAH4KI1Y57PFGQMUFZ3PRVM, 3XC1O3LBO82U2...","[A2LMQ4497NMK3S, A38DXFI1TZA295]",figurative,figurative,figurative
3,Young Turk,he quickly became a Young Turk in the company ...,figurative,a young person who has many new ideas and want...,"[0, 0]","[151.871, 56.632]","[337RC3OW0LI9F33S25IK4ALGTB0LVQ, 3X4MXAO0BW4XX...","[A2LMQ4497NMK3S, AX8NXTT8QMGHC]",figurative,figurative,figurative
4,Young Turk,the new employee was a Young Turk in the compa...,literal,a young person who has many new ideas and want...,"[1, 1]","[41.727, 47.025]","[31HQ4X3T38QTNBMO8ADFTN19U76LSL, 3L6L49WXWGDWJ...","[APRZ7BR8C0ZMQ, AX8NXTT8QMGHC]",literal,literal,literal

In [23]:
df[['idiom', 'meaning','instance', 'label', 'maxVote', 
    'gold_0', 'gold_1', 'AssignmentId', 'WorkerId', 'TimeMe'
    ]].to_csv("batch3_agg.csv", index=False)

In [27]:
golds = df[[f'gold_{i}' for i in range(NUM_ASSIGNMENTS)]].copy()
def g(row):
    for i in range(NUM_ASSIGNMENTS):
        row[f'gold_{i}'] = labels.index(row[f'gold_{i}'])
    return row
golds = golds.apply(g, axis=1)

In [28]:
from statsmodels.stats.inter_rater import aggregate_raters
from statsmodels.stats.inter_rater import fleiss_kappa
golds = aggregate_raters(golds)[0]
kappa = fleiss_kappa(golds, method='fleiss')
kappa

0.7485211106855313

In [29]:
len(df[df['maxVote'] == df['label']]) / len(df)

0.848