In [14]:
import pandas as pd
NUM_ASSIGNMENTS = 2

dfs = [pd.read_csv("../batch2/batch2_agg.csv"),
    pd.read_csv("../batch3/batch3_agg.csv"),
    pd.read_csv("../batch4/batch4+1_agg.csv")]

for i in range(3):
    dfs[i]['batch_num'] = i + 2

df = pd.concat(
    dfs,
    axis=0
)
df.sort_values(by=['idiom', 'label'], inplace=True)
df

,idiom,instance,label,meaning,maxVote,gold_0,gold_1,AssignmentId,WorkerId,TimeMe,batch_num
0,Achilles heel,"despite his intelligence, procrastination was ...",figurative,a vulnerable spot or weakness,figurative,figurative,figurative,"['3GS6S824S6DCIS6I4S3V348J5FHNWJ', '3LWJHTCVCS...","['A110KENBXU7SUJ', 'A38DXFI1TZA295']","[90.898, 24.979]",4
1,Achilles heel,"during the anatomy class, we studied his Achil...",literal,a vulnerable spot or weakness,literal,literal,literal,"['3FK0YFF9PFWCB8FMG9KQRJJIK9HVVY', '3SEPORI8W3...","['A110KENBXU7SUJ', 'A2LMQ4497NMK3S']","[32.455, 146.45]",4
2,Dutch uncle,"he gave me advice like a Dutch uncle, always s...",figurative,"criticize, scold or lecture someone",figurative,figurative,figurative,"['3U0SRXB7CTL7AWPW5YTPG502D02NRG', '3P529IW9KE...","['A1HKYY6XI2OHO1', 'AURYD2FH3FUOQ']","[116.593, 53.127]",4
0,Dutch uncle,he dressed up like a Dutch uncle for the histo...,literal,"criticize, scold or lecture someone",literal,literal,literal,"['3JBT3HLQFOIGF8N0VU0U6X7WMW7PZS', '3X3OR7WPZF...","['A1HKYY6XI2OHO1', 'A290OV59Q76QC8']","[115.322, 54.151]",3
3,Easter egg,"while playing the video game, he found an East...",figurative,a decorated or dyed egg usually given to child...,figurative,figurative,figurative,"['3JCG6DTRVJ6S1SNO8BW6F9L2MPNQQ5', '3E1QT0TDF5...","['A1HKYY6XI2OHO1', 'AURYD2FH3FUOQ']","[117.365, 56.789]",4
...,...,...,...,...,...,...,...,...,...,...,...
496,you reap what you sow,"after planting the seeds, the farmer knew it w...",literal,"if you do bad things to people, bad things wil...",literal,literal,literal,"['3TPZPLC3MGSFUFG7AN5L2W2H7193PA', '38SKSKU7RH...","['A38DXFI1TZA295', 'AX8NXTT8QMGHC']","[27.705, 109.552]",3
498,zero hour,the team was ready at zero hour to launch the ...,figurative,a time when a crucial decision or essential ac...,figurative,figurative,figurative,"['33LK57MYL9LDS03SNB4O12C79GESZB', '3YWRV122C8...","['A290OV59Q76QC8', 'A2TBXASXZIRNNW']","[61.004, 23.054]",3
648,zero hour,"the clock struck midnight, and we were at zero...",literal,a time when a crucial decision or essential ac...,tie,ambiguous,literal,"['336KAV9KY68KIBCPXANZWDQ15SQY22', '37C0GNLMHV...","['A110KENBXU7SUJ', 'A38DXFI1TZA295']","[42.775, 33.368]",4
649,zip it,"when she started talking about the secret, he ...",figurative,to ask someone to shut up,figurative,figurative,figurative,"['3EA3QWIZ4YBSCARXC7LSBC53FM5IT8', '3IFS6Q0HJY...","['A1HKYY6XI2OHO1', 'AURYD2FH3FUOQ']","[99.903, 55.22]",4
499,zip it,"before leaving the house, she made sure to zip...",literal,to ask someone to shut up,literal,literal,literal,"['37FMASSAYS7SGOXGCLU7BIZH9FQBIW', '35BLDD71IM...","['A290OV59Q76QC8', 'A2LMQ4497NMK3S']","[47.212, 156.678]",3

##### Inter-Annotator Agreement Rate

In [18]:
labels = ['figurative', 'literal', 'ambiguous', 'discard', 'tie']
golds = df[[f'gold_{i}' for i in range(NUM_ASSIGNMENTS)]].copy()
def g(row):
    for i in range(NUM_ASSIGNMENTS):
        row[f'gold_{i}'] = labels.index(row[f'gold_{i}'])
    return row
golds = golds.apply(g, axis=1)
golds.head()

   gold_0  gold_1
0       0       0
1       1       1
2       0       0
0       1       1
3       0       0

In [19]:
from statsmodels.stats.inter_rater import aggregate_raters
from statsmodels.stats.inter_rater import fleiss_kappa
golds = aggregate_raters(golds)[0]
kappa = fleiss_kappa(golds, method='fleiss')
kappa

0.721347265970035

##### Percentage of maxVote == intendedLabel

In [20]:
len(df[df['maxVote'] == df['label']]) / len(df)

0.8292857142857143